/* vim:set et sw=4 sts=4: */
#include "esgfile.h"
#include "ksupport.h"
#include <kmem.h>

#include "ivisa_sg_config.h"

#include "sg_com.h"
#include "sg_x2s_fun.h"
#include "x2s_macro.h"

X2S_FUN_DECL(ServiceComponentID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceComponentID)
X2S_GETNODECNT(ServiceComponentID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceComponentID)
X2S_SET_CNT(ServiceComponentID)
X2S_ALLOC_REC(ServiceComponentID)
X2S_FOREACH_NCNT(ServiceComponentID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceComponentID)
X2S_BRK_IF_BAD_NODE(ServiceComponentID)
X2S_FILL_VAL(kuint, ServiceComponentID)
X2S_GOTO_PRT_NODE(ServiceComponentID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceComponentID)

X2S_FUN_DECL(BroadcastPara)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BroadcastPara)
X2S_GETNODECNT(BroadcastPara)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BroadcastPara)
X2S_SET_CNT(BroadcastPara)
X2S_ALLOC_REC(BroadcastPara)
X2S_FOREACH_NCNT(BroadcastPara)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BroadcastPara)
X2S_BRK_IF_BAD_NODE(BroadcastPara)
X2S_FILL_ATT_DEF(kushort, onID, -1)
X2S_FILL_ATT_DEF(kushort, tsID, -1)
X2S_FILL_ATT(kuint, MediaType)
X2S_FILL_ATT(kuchar, ProtocolType)
X2S_FILL_ATT_DEF(kuint, eID, -1)
X2S_FILL_ATT(kuchar, TransportMode)
X2S_FILL_SUB(ServiceComponentID, ServiceComponentID)
X2S_GOTO_PRT_NODE(BroadcastPara)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BroadcastPara)


X2S_FUN_DECL(Version)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Version)
X2S_GETNODECNT(Version)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Version)
X2S_SET_CNT(Version)
X2S_ALLOC_REC(Version)
X2S_FOREACH_NCNT(Version)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Version)
X2S_BRK_IF_BAD_NODE(Version)
X2S_FILL_VAL(kpchar, Version)
X2S_GOTO_PRT_NODE(Version)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Version)


X2S_FUN_DECL(BDSType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BDSType)
X2S_GETNODECNT(BDSType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BDSType)
X2S_SET_CNT(BDSType)
X2S_ALLOC_REC(BDSType)
X2S_FOREACH_NCNT(BDSType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BDSType)
X2S_BRK_IF_BAD_NODE(BDSType)
X2S_FILL_SUB(Type, Type)
X2S_FILL_SUB(Version, Version)
X2S_GOTO_PRT_NODE(BDSType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BDSType)


X2S_FUN_DECL(SDP)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SDP)
X2S_GETNODECNT(SDP)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SDP)
X2S_SET_CNT(SDP)
X2S_ALLOC_REC(SDP)
X2S_FOREACH_NCNT(SDP)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SDP)
X2S_BRK_IF_BAD_NODE(SDP)
X2S_FILL_VAL(kpchar, SDP)
X2S_GOTO_PRT_NODE(SDP)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SDP)


X2S_FUN_DECL(SDPRef)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SDPRef)
X2S_GETNODECNT(SDPRef)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SDPRef)
X2S_SET_CNT(SDPRef)
X2S_ALLOC_REC(SDPRef)
X2S_FOREACH_NCNT(SDPRef)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SDPRef)
X2S_BRK_IF_BAD_NODE(SDPRef)
X2S_FILL_ATT(kpchar, uri)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(SDPRef)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SDPRef)


X2S_FUN_DECL(USBDRef)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(USBDRef)
X2S_GETNODECNT(USBDRef)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(USBDRef)
X2S_SET_CNT(USBDRef)
X2S_ALLOC_REC(USBDRef)
X2S_FOREACH_NCNT(USBDRef)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(USBDRef)
X2S_BRK_IF_BAD_NODE(USBDRef)
X2S_FILL_ATT(kpchar, uri)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(USBDRef)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(USBDRef)


X2S_FUN_DECL(ADPRef)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ADPRef)
X2S_GETNODECNT(ADPRef)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ADPRef)
X2S_SET_CNT(ADPRef)
X2S_ALLOC_REC(ADPRef)
X2S_FOREACH_NCNT(ADPRef)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ADPRef)
X2S_BRK_IF_BAD_NODE(ADPRef)
X2S_FILL_ATT(kpchar, uri)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(ADPRef)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ADPRef)


X2S_FUN_DECL(SessionDescription)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SessionDescription)
X2S_GETNODECNT(SessionDescription)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SessionDescription)
X2S_SET_CNT(SessionDescription)
X2S_ALLOC_REC(SessionDescription)
X2S_FOREACH_NCNT(SessionDescription)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SessionDescription)
X2S_BRK_IF_BAD_NODE(SessionDescription)
X2S_FILL_SUB(SDP, SDP)
X2S_FILL_SUB(SDPRef, SDPRef)
X2S_FILL_SUB(USBDRef, USBDRef)
X2S_FILL_SUB(ADPRef, ADPRef)
X2S_GOTO_PRT_NODE(SessionDescription)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SessionDescription)


X2S_FUN_DECL(File)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(File)
X2S_GETNODECNT(File)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(File)
X2S_SET_CNT(File)
X2S_ALLOC_REC(File)
X2S_FOREACH_NCNT(File)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(File)
X2S_BRK_IF_BAD_NODE(File)
X2S_FILL_ATT_(kpchar, Content_Location, "Content-Location")
X2S_FILL_ATT(kint, TOI)
X2S_FILL_ATT_(kulong, Content_Length, "Content-Length")
X2S_FILL_ATT_(kulong, Transfer_Length, "Transfer-Length")
X2S_FILL_ATT_(kpchar, Content_Type, "Content-Type")
X2S_FILL_ATT_(kpchar, Content_Encoding, "Content-Encoding")
X2S_FILL_ATT_(kpchar, Content_MD5, "Content-MD5")
X2S_FILL_ATT_(kuchar, FEC_OTI_FEC_Encoding_ID, "FEC-OTI-FEC-Encoding-ID")
X2S_FILL_ATT_(kulong, FEC_OTI_FEC_Instance_ID, "FEC-OTI-FEC-Instance-ID")
X2S_FILL_ATT_(kulong, FEC_OTI_Maximum_Source_Block_Length, "FEC-OTI-Maximum-Source-Block-Length")
X2S_FILL_ATT_(kulong, FEC_OTI_Encoding_Symbol_Length, "FEC-OTI-Encoding-Symbol-Length")
X2S_FILL_ATT_(kulong, FEC_OTI_Max_Number_of_Encoding_Symbols, "FEC-OTI-Max-Number-of-Encoding-Symbols")
X2S_FILL_ATT_(kpchar, FEC_OTI_Scheme_Specific_Info, "FEC-OTI-Scheme-Specific-Info")
X2S_GOTO_PRT_NODE(File)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(File)


X2S_FUN_DECL(FileDescription)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(FileDescription)
X2S_GETNODECNT(FileDescription)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(FileDescription)
X2S_SET_CNT(FileDescription)
X2S_ALLOC_REC(FileDescription)
X2S_FOREACH_NCNT(FileDescription)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(FileDescription)
X2S_BRK_IF_BAD_NODE(FileDescription)
X2S_FILL_ATT_(kpchar, Content_Type, "Content-Type")
X2S_FILL_ATT_(kpchar, Content_Encoding, "Content-Encoding")
X2S_FILL_ATT_(kuchar, FEC_OTI_FEC_Encoding_ID, "FEC-OTI-FEC-Encoding-ID")
X2S_FILL_ATT_(kulong, FEC_OTI_FEC_Instance_ID, "FEC-OTI-FEC-Instance-ID")
X2S_FILL_ATT_(kulong, FEC_OTI_Maximum_Source_Block_Length, "FEC-OTI-Maximum-Source-Block-Length")
X2S_FILL_ATT_(kulong, FEC_OTI_Encoding_Symbol_Length, "FEC-OTI-Encoding-Symbol-Length")
X2S_FILL_ATT_(kulong, FEC_OTI_Max_Number_of_Encoding_Symbols, "FEC-OTI-Max-Number-of-Encoding-Symbols")
X2S_FILL_ATT_(kchar, FEC_OTI_Scheme_Specific_Info, "FEC-OTI-Scheme-Specific-Info")
// X2S_FILL_SUB(File, File)
X2S_GOTO_PRT_NODE(FileDescription)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(FileDescription)


X2S_FUN_DECL(BroadcastServiceDelivery)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BroadcastServiceDelivery)
X2S_GETNODECNT(BroadcastServiceDelivery)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BroadcastServiceDelivery)
X2S_SET_CNT(BroadcastServiceDelivery)
X2S_ALLOC_REC(BroadcastServiceDelivery)
X2S_FOREACH_NCNT(BroadcastServiceDelivery)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BroadcastServiceDelivery)
X2S_BRK_IF_BAD_NODE(BroadcastServiceDelivery)
X2S_FILL_SUB(BDSType, BDSType)
X2S_FILL_SUB(SessionDescription, SessionDescription)
X2S_FILL_SUB(FileDescription, FileDescription)
X2S_GOTO_PRT_NODE(BroadcastServiceDelivery)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BroadcastServiceDelivery)


X2S_FUN_DECL(AccessType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AccessType)
X2S_GETNODECNT(AccessType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AccessType)
X2S_SET_CNT(AccessType)
X2S_ALLOC_REC(AccessType)
X2S_FOREACH_NCNT(AccessType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AccessType)
X2S_BRK_IF_BAD_NODE(AccessType)
X2S_FILL_SUB(BroadcastServiceDelivery, BroadcastServiceDelivery)
X2S_GOTO_PRT_NODE(AccessType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AccessType)


X2S_FUN_DECL(KeyManagementSystem)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(KeyManagementSystem)
X2S_GETNODECNT(KeyManagementSystem)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(KeyManagementSystem)
X2S_SET_CNT(KeyManagementSystem)
X2S_ALLOC_REC(KeyManagementSystem)
X2S_FOREACH_NCNT(KeyManagementSystem)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(KeyManagementSystem)
X2S_BRK_IF_BAD_NODE(KeyManagementSystem)
X2S_FILL_ATT(kchar, kmsType)
X2S_FILL_ATT(kchar, protectionType)
X2S_FILL_SUB(ProtectionKeyID, ProtectionKeyID)
X2S_FILL_SUB(PermissionsIssuerURI, PermissionsIssuerURI)
X2S_FILL_SUB(TerminalBindingKeyID, TerminalBindingKeyID)
X2S_GOTO_PRT_NODE(KeyManagementSystem)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(KeyManagementSystem)


X2S_FUN_DECL(EncryptionType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(EncryptionType)
X2S_GETNODECNT(EncryptionType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(EncryptionType)
X2S_SET_CNT(EncryptionType)
X2S_ALLOC_REC(EncryptionType)
X2S_FOREACH_NCNT(EncryptionType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(EncryptionType)
X2S_BRK_IF_BAD_NODE(EncryptionType)
X2S_FILL_VAL(kchar, EncryptionType)
X2S_GOTO_PRT_NODE(EncryptionType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(EncryptionType)


X2S_FUN_DECL(DownloadFile)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(DownloadFile)
X2S_GETNODECNT(DownloadFile)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(DownloadFile)
X2S_SET_CNT(DownloadFile)
X2S_ALLOC_REC(DownloadFile)
X2S_FOREACH_NCNT(DownloadFile)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(DownloadFile)
X2S_BRK_IF_BAD_NODE(DownloadFile)
X2S_FILL_SUB(MIMEType, MIMEType)
X2S_GOTO_PRT_NODE(DownloadFile)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(DownloadFile)


X2S_FUN_DECL(TerminalCapabilityRequirement)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TerminalCapabilityRequirement)
X2S_GETNODECNT(TerminalCapabilityRequirement)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TerminalCapabilityRequirement)
X2S_SET_CNT(TerminalCapabilityRequirement)
X2S_ALLOC_REC(TerminalCapabilityRequirement)
X2S_FOREACH_NCNT(TerminalCapabilityRequirement)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TerminalCapabilityRequirement)
X2S_BRK_IF_BAD_NODE(TerminalCapabilityRequirement)
X2S_FILL_SUB(Video, Video)
X2S_FILL_SUB(Audio, Audio)
X2S_FILL_SUB(DownloadFile, DownloadFile)
X2S_GOTO_PRT_NODE(TerminalCapabilityRequirement)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TerminalCapabilityRequirement)


X2S_FUN_DECL(BandwidthRequirement)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BandwidthRequirement)
X2S_GETNODECNT(BandwidthRequirement)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BandwidthRequirement)
X2S_SET_CNT(BandwidthRequirement)
X2S_ALLOC_REC(BandwidthRequirement)
X2S_FOREACH_NCNT(BandwidthRequirement)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BandwidthRequirement)
X2S_BRK_IF_BAD_NODE(BandwidthRequirement)
X2S_FILL_VAL(kchar, BandwidthRequirement)
X2S_GOTO_PRT_NODE(BandwidthRequirement)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BandwidthRequirement)


X2S_FUN_DECL(ServiceClass)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceClass)
X2S_GETNODECNT(ServiceClass)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceClass)
X2S_SET_CNT(ServiceClass)
X2S_ALLOC_REC(ServiceClass)
X2S_FOREACH_NCNT(ServiceClass)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceClass)
X2S_BRK_IF_BAD_NODE(ServiceClass)
X2S_FILL_VAL(kpchar, ServiceClass)
X2S_GOTO_PRT_NODE(ServiceClass)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceClass)

#if 0
X2S_FUN_DECL(Access)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Access)
X2S_GETNODECNT(Access)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Access)
X2S_SET_CNT(Access)
X2S_ALLOC_REC(Access)
X2S_FOREACH_NCNT(Access)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Access)
X2S_BRK_IF_BAD_NODE(Access)
X2S_FILL_SUB(AccessType, AccessType)
X2S_FILL_SUB(KeyManagementSystem, KeyManagementSystem)
X2S_FILL_SUB(EncryptionType, EncryptionType)
X2S_FILL_SUB(ServiceReference, ServiceReference)
X2S_FILL_SUB(ScheduleReference, ScheduleReference)
X2S_FILL_SUB(TerminalCapabilityRequirement, TerminalCapabilityRequirement)
X2S_FILL_SUB(BandwidthRequirement, BandwidthRequirement)
X2S_FILL_SUB(ServiceClass, ServiceClass)
X2S_FILL_SUB(PreviewDataReference, PreviewDataReference)
X2S_FILL_SUB(NotificationReception, NotificationReception)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(Access)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Access)
#endif


X2S_FUN_DECL(Type)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Type)
X2S_GETNODECNT(Type)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Type)
X2S_SET_CNT(Type)
X2S_ALLOC_REC(Type)
X2S_FOREACH_NCNT(Type)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Type)
X2S_BRK_IF_BAD_NODE(Type)
X2S_FILL_VAL(kuchar, Type)
X2S_GOTO_PRT_NODE(Type)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Type)


X2S_FUN_DECL(Name)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Name)
X2S_GETNODECNT(Name)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Name)
X2S_SET_CNT(Name)
X2S_ALLOC_REC(Name)
X2S_FOREACH_NCNT(Name)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Name)
X2S_BRK_IF_BAD_NODE(Name)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, Name)
X2S_GOTO_PRT_NODE(Name)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Name)


X2S_FUN_DECL(StartTime)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(StartTime)
X2S_GETNODECNT(StartTime)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(StartTime)
X2S_SET_CNT(StartTime)
X2S_ALLOC_REC(StartTime)
X2S_FOREACH_NCNT(StartTime)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(StartTime)
X2S_BRK_IF_BAD_NODE(StartTime)
X2S_FILL_VAL(kpchar, StartTime)
X2S_GOTO_PRT_NODE(StartTime)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(StartTime)


X2S_FUN_DECL(EndTime)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(EndTime)
X2S_GETNODECNT(EndTime)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(EndTime)
X2S_SET_CNT(EndTime)
X2S_ALLOC_REC(EndTime)
X2S_FOREACH_NCNT(EndTime)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(EndTime)
X2S_BRK_IF_BAD_NODE(EndTime)
X2S_FILL_VAL(kpchar, EndTime)
X2S_GOTO_PRT_NODE(EndTime)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(EndTime)


X2S_FUN_DECL(Description)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Description)
X2S_GETNODECNT(Description)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Description)
X2S_SET_CNT(Description)
X2S_ALLOC_REC(Description)
X2S_FOREACH_NCNT(Description)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Description)
X2S_BRK_IF_BAD_NODE(Description)
X2S_FILL_ATT(kpchar, text)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, Description)
X2S_GOTO_PRT_NODE(Description)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Description)


X2S_FUN_DECL(Extension)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Extension)
X2S_GETNODECNT(Extension)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Extension)
X2S_SET_CNT(Extension)
X2S_ALLOC_REC(Extension)
X2S_FOREACH_NCNT(Extension)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Extension)
X2S_BRK_IF_BAD_NODE(Extension)
X2S_FILL_ATT(kpchar, url)
X2S_FILL_SUB(Description, Description)
X2S_GOTO_PRT_NODE(Extension)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Extension)


X2S_FUN_DECL(PreviewDataReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PreviewDataReference)
X2S_GETNODECNT(PreviewDataReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PreviewDataReference)
X2S_SET_CNT(PreviewDataReference)
X2S_ALLOC_REC(PreviewDataReference)
X2S_FOREACH_NCNT(PreviewDataReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PreviewDataReference)
X2S_BRK_IF_BAD_NODE(PreviewDataReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_ATT(kuchar, usage)
X2S_GOTO_PRT_NODE(PreviewDataReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PreviewDataReference)


X2S_FUN_DECL(Genre)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Genre)
X2S_GETNODECNT(Genre)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Genre)
X2S_SET_CNT(Genre)
X2S_ALLOC_REC(Genre)
X2S_FOREACH_NCNT(Genre)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Genre)
X2S_BRK_IF_BAD_NODE(Genre)
X2S_FILL_ATT(kpchar, type)
X2S_FILL_ATT(kpchar, href)
X2S_FILL_VAL(kpchar, Genre)
X2S_GOTO_PRT_NODE(Genre)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Genre)


X2S_FUN_DECL(TextLanguage)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TextLanguage)
X2S_GETNODECNT(TextLanguage)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TextLanguage)
X2S_SET_CNT(TextLanguage)
X2S_ALLOC_REC(TextLanguage)
X2S_FOREACH_NCNT(TextLanguage)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TextLanguage)
X2S_BRK_IF_BAD_NODE(TextLanguage)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kpchar, languageSDPTag)
X2S_FILL_VAL(kpchar, TextLanguage)
X2S_GOTO_PRT_NODE(TextLanguage)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TextLanguage)


X2S_FUN_DECL(ParentalRating)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ParentalRating)
X2S_GETNODECNT(ParentalRating)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ParentalRating)
X2S_SET_CNT(ParentalRating)
X2S_ALLOC_REC(ParentalRating)
X2S_FOREACH_NCNT(ParentalRating)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ParentalRating)
X2S_BRK_IF_BAD_NODE(ParentalRating)
X2S_FILL_ATT(kpchar, ratingSystem)
X2S_FILL_VAL(kpchar, ParentalRating)
X2S_GOTO_PRT_NODE(ParentalRating)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ParentalRating)


X2S_FUN_DECL(TargetUserProfile)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TargetUserProfile)
X2S_GETNODECNT(TargetUserProfile)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TargetUserProfile)
X2S_SET_CNT(TargetUserProfile)
X2S_ALLOC_REC(TargetUserProfile)
X2S_FOREACH_NCNT(TargetUserProfile)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TargetUserProfile)
X2S_BRK_IF_BAD_NODE(TargetUserProfile)
X2S_FILL_ATT(kpchar, attributeName)
X2S_FILL_ATT(kpchar, attributeValue)
X2S_GOTO_PRT_NODE(TargetUserProfile)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TargetUserProfile)


X2S_FUN_DECL(ProtectionKeyID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ProtectionKeyID)
X2S_GETNODECNT(ProtectionKeyID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ProtectionKeyID)
X2S_SET_CNT(ProtectionKeyID)
X2S_ALLOC_REC(ProtectionKeyID)
X2S_FOREACH_NCNT(ProtectionKeyID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ProtectionKeyID)
X2S_BRK_IF_BAD_NODE(ProtectionKeyID)
X2S_FILL_ATT(kuchar, type)
X2S_FILL_VAL(kpchar, ProtectionKeyID)
X2S_GOTO_PRT_NODE(ProtectionKeyID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ProtectionKeyID)


X2S_FUN_DECL(AudioLanguage)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AudioLanguage)
X2S_GETNODECNT(AudioLanguage)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AudioLanguage)
X2S_SET_CNT(AudioLanguage)
X2S_ALLOC_REC(AudioLanguage)
X2S_FOREACH_NCNT(AudioLanguage)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AudioLanguage)
X2S_BRK_IF_BAD_NODE(AudioLanguage)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kpchar, languageSDPTag)
X2S_FILL_VAL(kpchar, AudioLanguage)
X2S_GOTO_PRT_NODE(AudioLanguage)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AudioLanguage)

X2S_FUN_DECL(IPBroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(IPBroadcastDelivery)
X2S_GETNODECNT(IPBroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(IPBroadcastDelivery)
X2S_SET_CNT(IPBroadcastDelivery)
X2S_ALLOC_REC(IPBroadcastDelivery)
X2S_FOREACH_NCNT(IPBroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(IPBroadcastDelivery)
X2S_BRK_IF_BAD_NODE(IPBroadcastDelivery)
X2S_FILL_ATT(kuint, port)
X2S_FILL_ATT(kpchar, address)
X2S_GOTO_PRT_NODE(IPBroadcastDelivery)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(IPBroadcastDelivery)

X2S_FUN_DECL(BroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BroadcastDelivery)
X2S_GETNODECNT(BroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BroadcastDelivery)
X2S_SET_CNT(BroadcastDelivery)
X2S_ALLOC_REC(BroadcastDelivery)
X2S_FOREACH_NCNT(BroadcastDelivery)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BroadcastDelivery)
X2S_BRK_IF_BAD_NODE(BroadcastDelivery)
X2S_FILL_SUB(ServiceComponentID, ServiceComponentID)
X2S_GOTO_PRT_NODE(BroadcastDelivery)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BroadcastDelivery)


X2S_FUN_DECL(RequestURL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(RequestURL)
X2S_GETNODECNT(RequestURL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(RequestURL)
X2S_SET_CNT(RequestURL)
X2S_ALLOC_REC(RequestURL)
X2S_FOREACH_NCNT(RequestURL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(RequestURL)
X2S_BRK_IF_BAD_NODE(RequestURL)
X2S_FILL_VAL(kpchar, RequestURL)
X2S_GOTO_PRT_NODE(RequestURL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(RequestURL)


X2S_FUN_DECL(PollURL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PollURL)
X2S_GETNODECNT(PollURL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PollURL)
X2S_SET_CNT(PollURL)
X2S_ALLOC_REC(PollURL)
X2S_FOREACH_NCNT(PollURL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PollURL)
X2S_BRK_IF_BAD_NODE(PollURL)
X2S_FILL_VAL(kpchar, PollURL)
X2S_GOTO_PRT_NODE(PollURL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PollURL)

X2S_FUN_DECL(NotificationReception)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(NotificationReception)
X2S_GETNODECNT(NotificationReception)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(NotificationReception)
X2S_SET_CNT(NotificationReception)
X2S_ALLOC_REC(NotificationReception)
X2S_FOREACH_NCNT(NotificationReception)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(NotificationReception)
X2S_BRK_IF_BAD_NODE(NotificationReception)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(RequestURL, RequestURL)
X2S_FILL_SUB(PollURL, PollURL)
X2S_FILL_SUB(BroadcastDelivery, BroadcastDelivery)
X2S_FILL_SUB(IPBroadcastDelivery, IPBroadcastDelivery)
X2S_GOTO_PRT_NODE(NotificationReception)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(NotificationReception)

X2S_FUN_DECL(PurchaseItemReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseItemReference)
X2S_GETNODECNT(PurchaseItemReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseItemReference)
X2S_SET_CNT(PurchaseItemReference)
X2S_ALLOC_REC(PurchaseItemReference)
X2S_FOREACH_NCNT(PurchaseItemReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseItemReference)
X2S_BRK_IF_BAD_NODE(PurchaseItemReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(PurchaseItemReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseItemReference)


X2S_FUN_DECL(PresentationWindowIDRef)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PresentationWindowIDRef)
X2S_GETNODECNT(PresentationWindowIDRef)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PresentationWindowIDRef)
X2S_SET_CNT(PresentationWindowIDRef)
X2S_ALLOC_REC(PresentationWindowIDRef)
X2S_FOREACH_NCNT(PresentationWindowIDRef)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PresentationWindowIDRef)
X2S_BRK_IF_BAD_NODE(PresentationWindowIDRef)
X2S_FILL_VAL(kuint, PresentationWindowIDRef)
X2S_GOTO_PRT_NODE(PresentationWindowIDRef)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PresentationWindowIDRef)


X2S_FUN_DECL(cc)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(cc)
X2S_GETNODECNT(cc)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(cc)
X2S_SET_CNT(cc)
X2S_ALLOC_REC(cc)
X2S_FOREACH_NCNT(cc)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(cc)
X2S_BRK_IF_BAD_NODE(cc)
X2S_FILL_VAL(kushort, cc)
X2S_GOTO_PRT_NODE(cc)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(cc)


X2S_FUN_DECL(name_area)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(name_area)
X2S_GETNODECNT(name_area)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(name_area)
X2S_SET_CNT(name_area)
X2S_ALLOC_REC(name_area)
X2S_FOREACH_NCNT(name_area)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(name_area)
X2S_BRK_IF_BAD_NODE(name_area)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, name_area)
X2S_GOTO_PRT_NODE(name_area)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(name_area)


X2S_FUN_DECL(ZipCode)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ZipCode)
X2S_GETNODECNT(ZipCode)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ZipCode)
X2S_SET_CNT(ZipCode)
X2S_ALLOC_REC(ZipCode)
X2S_FOREACH_NCNT(ZipCode)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ZipCode)
X2S_BRK_IF_BAD_NODE(ZipCode)
X2S_FILL_VAL(kpchar, ZipCode)
X2S_GOTO_PRT_NODE(ZipCode)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ZipCode)


X2S_FUN_DECL(PP2CellID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PP2CellID)
X2S_GETNODECNT(PP2CellID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PP2CellID)
X2S_SET_CNT(PP2CellID)
X2S_ALLOC_REC(PP2CellID)
X2S_FOREACH_NCNT(PP2CellID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PP2CellID)
X2S_BRK_IF_BAD_NODE(PP2CellID)
X2S_FILL_VAL(kint, PP2CellID)
X2S_GOTO_PRT_NODE(PP2CellID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PP2CellID)


X2S_FUN_DECL(CellArea)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(CellArea)
X2S_GETNODECNT(CellArea)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(CellArea)
X2S_SET_CNT(CellArea)
X2S_ALLOC_REC(CellArea)
X2S_FOREACH_NCNT(CellArea)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(CellArea)
X2S_BRK_IF_BAD_NODE(CellArea)
X2S_FILL_ATT(kushort, value)
X2S_FILL_SUB(PP2CellID, PP2CellID)
X2S_GOTO_PRT_NODE(CellArea)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(CellArea)


X2S_FUN_DECL(CellTargetArea)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(CellTargetArea)
X2S_GETNODECNT(CellTargetArea)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(CellTargetArea)
X2S_SET_CNT(CellTargetArea)
X2S_ALLOC_REC(CellTargetArea)
X2S_FOREACH_NCNT(CellTargetArea)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(CellTargetArea)
X2S_BRK_IF_BAD_NODE(CellTargetArea)
X2S_FILL_ATT(kuchar, type)
X2S_FILL_SUB(CellArea, CellArea)
X2S_GOTO_PRT_NODE(CellTargetArea)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(CellTargetArea)


X2S_FUN_DECL(TargetArea)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TargetArea)
X2S_GETNODECNT(TargetArea)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TargetArea)
X2S_SET_CNT(TargetArea)
X2S_ALLOC_REC(TargetArea)
X2S_FOREACH_NCNT(TargetArea)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TargetArea)
X2S_BRK_IF_BAD_NODE(TargetArea)
X2S_FILL_SUB(shape, shape)
X2S_FILL_SUB(cc, cc)
X2S_FILL_SUB(name_area, name_area)
X2S_FILL_SUB(ZipCode, ZipCode)
X2S_FILL_SUB(CellTargetArea, CellTargetArea)
X2S_GOTO_PRT_NODE(TargetArea)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TargetArea)


X2S_FUN_DECL(hor_acc)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(hor_acc)
X2S_GETNODECNT(hor_acc)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(hor_acc)
X2S_SET_CNT(hor_acc)
X2S_ALLOC_REC(hor_acc)
X2S_FOREACH_NCNT(hor_acc)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(hor_acc)
X2S_BRK_IF_BAD_NODE(hor_acc)
X2S_FILL_VAL(kpchar, hor_acc)
X2S_GOTO_PRT_NODE(hor_acc)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(hor_acc)


X2S_FUN_DECL(BroadcastArea)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BroadcastArea)
X2S_GETNODECNT(BroadcastArea)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BroadcastArea)
X2S_SET_CNT(BroadcastArea)
X2S_ALLOC_REC(BroadcastArea)
X2S_FOREACH_NCNT(BroadcastArea)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BroadcastArea)
X2S_BRK_IF_BAD_NODE(BroadcastArea)
X2S_FILL_ATT(kbool, polarity)
X2S_FILL_SUB(TargetArea, TargetArea)
X2S_FILL_SUB(hor_acc, hor_acc)
X2S_GOTO_PRT_NODE(BroadcastArea)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BroadcastArea)


X2S_FUN_DECL(Country)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Country)
X2S_GETNODECNT(Country)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Country)
X2S_SET_CNT(Country)
X2S_ALLOC_REC(Country)
X2S_FOREACH_NCNT(Country)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Country)
X2S_BRK_IF_BAD_NODE(Country)
X2S_FILL_VAL(kpchar, Country)
X2S_GOTO_PRT_NODE(Country)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Country)


X2S_FUN_DECL(Language)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Language)
X2S_GETNODECNT(Language)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Language)
X2S_SET_CNT(Language)
X2S_ALLOC_REC(Language)
X2S_FOREACH_NCNT(Language)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Language)
X2S_BRK_IF_BAD_NODE(Language)
X2S_FILL_VAL(kpchar, Language)
X2S_GOTO_PRT_NODE(Language)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Language)


X2S_FUN_DECL(PreviewDataIDRef)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PreviewDataIDRef)
X2S_GETNODECNT(PreviewDataIDRef)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PreviewDataIDRef)
X2S_SET_CNT(PreviewDataIDRef)
X2S_ALLOC_REC(PreviewDataIDRef)
X2S_FOREACH_NCNT(PreviewDataIDRef)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PreviewDataIDRef)
X2S_BRK_IF_BAD_NODE(PreviewDataIDRef)
X2S_FILL_VAL(kpchar, PreviewDataIDRef)
X2S_GOTO_PRT_NODE(PreviewDataIDRef)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PreviewDataIDRef)


X2S_FUN_DECL(TermsOfUseText)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TermsOfUseText)
X2S_GETNODECNT(TermsOfUseText)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TermsOfUseText)
X2S_SET_CNT(TermsOfUseText)
X2S_ALLOC_REC(TermsOfUseText)
X2S_FOREACH_NCNT(TermsOfUseText)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TermsOfUseText)
X2S_BRK_IF_BAD_NODE(TermsOfUseText)
X2S_FILL_VAL(kpchar, TermsOfUseText)
X2S_GOTO_PRT_NODE(TermsOfUseText)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TermsOfUseText)


X2S_FUN_DECL(TermsOfUse)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TermsOfUse)
X2S_GETNODECNT(TermsOfUse)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TermsOfUse)
X2S_SET_CNT(TermsOfUse)
X2S_ALLOC_REC(TermsOfUse)
X2S_FOREACH_NCNT(TermsOfUse)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TermsOfUse)
X2S_BRK_IF_BAD_NODE(TermsOfUse)
X2S_FILL_ATT(kuchar, type)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kbool, userConsentRequired)
X2S_FILL_SUB(Country, Country)
X2S_FILL_SUB(Language, Language)
X2S_FILL_SUB(PreviewDataIDRef, PreviewDataIDRef)
X2S_FILL_SUB(TermsOfUseText, TermsOfUseText)
X2S_GOTO_PRT_NODE(TermsOfUse)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TermsOfUse)




X2S_FUN_DECL(ServiceReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceReference)
X2S_GETNODECNT(ServiceReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceReference)
X2S_SET_CNT(ServiceReference)
X2S_ALLOC_REC(ServiceReference)
X2S_FOREACH_NCNT(ServiceReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceReference)
X2S_BRK_IF_BAD_NODE(ServiceReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_ATT(kpchar, audioLanguageIDRef)
X2S_FILL_ATT(kpchar, textLanguageIDRef)
X2S_FILL_ATT(kushort, weight)
X2S_GOTO_PRT_NODE(ServiceReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceReference)


X2S_FUN_DECL(Length)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Length)
X2S_GETNODECNT(Length)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Length)
X2S_SET_CNT(Length)
X2S_ALLOC_REC(Length)
X2S_FOREACH_NCNT(Length)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Length)
X2S_BRK_IF_BAD_NODE(Length)
X2S_FILL_VAL(kuint, Length)
X2S_GOTO_PRT_NODE(Length)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Length)

#if 0
X2S_FUN_DECL(Content)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Content)
X2S_GETNODECNT(Content)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Content)
X2S_SET_CNT(Content)
X2S_ALLOC_REC(Content)
X2S_FOREACH_NCNT(Content)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Content)
X2S_BRK_IF_BAD_NODE(Content)
X2S_FILL_ATT(kpchar, globalContentID)
X2S_FILL_ATT(kbool, emergency)
X2S_FILL_ATT(kbool, serviceContentProtection)
X2S_FILL_ATT(kpchar, baseCID)
X2S_FILL_SUB(ServiceReference, ServiceReference)
X2S_FILL_SUB(ProtectionKeyID, ProtectionKeyID)
X2S_FILL_SUB(Name, Name)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(StartTime, StartTime)
X2S_FILL_SUB(EndTime, EndTime)
X2S_FILL_SUB(AudioLanguage, AudioLanguage)
X2S_FILL_SUB(TextLanguage, TextLanguage)
X2S_FILL_SUB(Length, Length)
X2S_FILL_SUB(ParentalRating, ParentalRating)
X2S_FILL_SUB(TargetUserProfile, TargetUserProfile)
X2S_FILL_SUB(Genre, Genre)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(PreviewDataReference, PreviewDataReference)
X2S_FILL_SUB(BroadcastArea, BroadcastArea)
X2S_FILL_SUB(TermsOfUse, TermsOfUse)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(Content)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Content)
#endif


X2S_FUN_DECL(InteractivityType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(InteractivityType)
X2S_GETNODECNT(InteractivityType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(InteractivityType)
X2S_SET_CNT(InteractivityType)
X2S_ALLOC_REC(InteractivityType)
X2S_FOREACH_NCNT(InteractivityType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(InteractivityType)
X2S_BRK_IF_BAD_NODE(InteractivityType)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, InteractivityType)
X2S_GOTO_PRT_NODE(InteractivityType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(InteractivityType)


X2S_FUN_DECL(InteractivityWindow)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(InteractivityWindow)
X2S_GETNODECNT(InteractivityWindow)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(InteractivityWindow)
X2S_SET_CNT(InteractivityWindow)
X2S_ALLOC_REC(InteractivityWindow)
X2S_FOREACH_NCNT(InteractivityWindow)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(InteractivityWindow)
X2S_BRK_IF_BAD_NODE(InteractivityWindow)
X2S_FILL_ATT(kuint, startTime)
X2S_FILL_ATT(kuint, endTime)
X2S_FILL_VAL(kpchar, InteractivityWindow)
X2S_GOTO_PRT_NODE(InteractivityWindow)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(InteractivityWindow)


X2S_FUN_DECL(InteractiveDelivery)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(InteractiveDelivery)
X2S_GETNODECNT(InteractiveDelivery)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(InteractiveDelivery)
X2S_SET_CNT(InteractiveDelivery)
X2S_ALLOC_REC(InteractiveDelivery)
X2S_FOREACH_NCNT(InteractiveDelivery)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(InteractiveDelivery)
X2S_BRK_IF_BAD_NODE(InteractiveDelivery)
X2S_FILL_ATT(kchar, interactivtyMediaURL)
X2S_FILL_ATT(kbool, pushDelivery)
X2S_FILL_VAL(kpchar, InteractiveDelivery)
X2S_GOTO_PRT_NODE(InteractiveDelivery)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(InteractiveDelivery)


X2S_FUN_DECL(BackOffTiming)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BackOffTiming)
X2S_GETNODECNT(BackOffTiming)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BackOffTiming)
X2S_SET_CNT(BackOffTiming)
X2S_ALLOC_REC(BackOffTiming)
X2S_FOREACH_NCNT(BackOffTiming)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BackOffTiming)
X2S_BRK_IF_BAD_NODE(BackOffTiming)
X2S_FILL_ATT(kint, offsetTime)
X2S_FILL_ATT(kint, randomTime)
X2S_GOTO_PRT_NODE(BackOffTiming)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BackOffTiming)


#if 0
X2S_FUN_DECL(InteractivityData)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(InteractivityData)
X2S_GETNODECNT(InteractivityData)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(InteractivityData)
X2S_SET_CNT(InteractivityData)
X2S_ALLOC_REC(InteractivityData)
X2S_FOREACH_NCNT(InteractivityData)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(InteractivityData)
X2S_BRK_IF_BAD_NODE(InteractivityData)
X2S_FILL_ATT(kbool, preListenIndicator)
X2S_FILL_ATT(kpchar, interactivityMediaDocumentPointer)
X2S_FILL_SUB(InteractivityType, InteractivityType)
X2S_FILL_SUB(ServiceReference, ServiceReference)
X2S_FILL_SUB(ContentReference, ContentReference)
X2S_FILL_SUB(ScheduleReference, ScheduleReference)
X2S_FILL_SUB(InteractivityWindow, InteractivityWindow)
X2S_FILL_SUB(InteractiveDelivery, InteractiveDelivery)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(BackOffTiming, BackOffTiming)
X2S_FILL_SUB(TermsOfUse, TermsOfUse)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(InteractivityData)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(InteractivityData)
#endif


X2S_FUN_DECL(ContactInfo)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ContactInfo)
X2S_GETNODECNT(ContactInfo)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ContactInfo)
X2S_SET_CNT(ContactInfo)
X2S_ALLOC_REC(ContactInfo)
X2S_FOREACH_NCNT(ContactInfo)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ContactInfo)
X2S_BRK_IF_BAD_NODE(ContactInfo)
X2S_FILL_VAL(kpchar, ContactInfo)
X2S_GOTO_PRT_NODE(ContactInfo)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ContactInfo)


X2S_FUN_DECL(PortalURL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PortalURL)
X2S_GETNODECNT(PortalURL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PortalURL)
X2S_SET_CNT(PortalURL)
X2S_ALLOC_REC(PortalURL)
X2S_FOREACH_NCNT(PortalURL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PortalURL)
X2S_BRK_IF_BAD_NODE(PortalURL)
X2S_FILL_ATT(kuchar, supportedService)
X2S_FILL_VAL(kpchar, PortalURL)
X2S_GOTO_PRT_NODE(PortalURL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PortalURL)


X2S_FUN_DECL(PurchaseURL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseURL)
X2S_GETNODECNT(PurchaseURL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseURL)
X2S_SET_CNT(PurchaseURL)
X2S_ALLOC_REC(PurchaseURL)
X2S_FOREACH_NCNT(PurchaseURL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseURL)
X2S_BRK_IF_BAD_NODE(PurchaseURL)
X2S_FILL_VAL(kpchar, PurchaseURL)
X2S_GOTO_PRT_NODE(PurchaseURL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseURL)

#if 0
X2S_FUN_DECL(PurchaseChannel)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseChannel)
X2S_GETNODECNT(PurchaseChannel)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseChannel)
X2S_SET_CNT(PurchaseChannel)
X2S_ALLOC_REC(PurchaseChannel)
X2S_FOREACH_NCNT(PurchaseChannel)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseChannel)
X2S_BRK_IF_BAD_NODE(PurchaseChannel)
X2S_FILL_ATT(kpchar, rightsIssuerURI)
X2S_FILL_SUB(Name, Name)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(ContactInfo, ContactInfo)
X2S_FILL_SUB(PortalURL, PortalURL)
X2S_FILL_SUB(PurchaseURL, PurchaseURL)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(PurchaseChannel)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseChannel)
#endif


X2S_FUN_DECL(MonetaryPrice)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MonetaryPrice)
X2S_GETNODECNT(MonetaryPrice)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MonetaryPrice)
X2S_SET_CNT(MonetaryPrice)
X2S_ALLOC_REC(MonetaryPrice)
X2S_FOREACH_NCNT(MonetaryPrice)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MonetaryPrice)
X2S_BRK_IF_BAD_NODE(MonetaryPrice)
X2S_FILL_ATT(kpchar, currency)
X2S_FILL_VAL(kpchar, MonetaryPrice)
X2S_GOTO_PRT_NODE(MonetaryPrice)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MonetaryPrice)


X2S_FUN_DECL(TotalNumberToken)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TotalNumberToken)
X2S_GETNODECNT(TotalNumberToken)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TotalNumberToken)
X2S_SET_CNT(TotalNumberToken)
X2S_ALLOC_REC(TotalNumberToken)
X2S_FOREACH_NCNT(TotalNumberToken)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TotalNumberToken)
X2S_BRK_IF_BAD_NODE(TotalNumberToken)
X2S_FILL_ATT(kuchar, tokenType)
X2S_FILL_ATT(kushort, consumptionAmount)
X2S_FILL_ATT(kuchar, consumptionUnit)
X2S_FILL_ATT(kushort, maxReplay)
X2S_FILL_VAL(kushort, TotalNumberToken)
X2S_GOTO_PRT_NODE(TotalNumberToken)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TotalNumberToken)


X2S_FUN_DECL(SubscriptionPeriod)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SubscriptionPeriod)
X2S_GETNODECNT(SubscriptionPeriod)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SubscriptionPeriod)
X2S_SET_CNT(SubscriptionPeriod)
X2S_ALLOC_REC(SubscriptionPeriod)
X2S_FOREACH_NCNT(SubscriptionPeriod)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SubscriptionPeriod)
X2S_BRK_IF_BAD_NODE(SubscriptionPeriod)
X2S_FILL_VAL(kpchar, SubscriptionPeriod)
X2S_GOTO_PRT_NODE(SubscriptionPeriod)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SubscriptionPeriod)


X2S_FUN_DECL(PriceInfo)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PriceInfo)
X2S_GETNODECNT(PriceInfo)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PriceInfo)
X2S_SET_CNT(PriceInfo)
X2S_ALLOC_REC(PriceInfo)
X2S_FOREACH_NCNT(PriceInfo)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PriceInfo)
X2S_BRK_IF_BAD_NODE(PriceInfo)
X2S_FILL_ATT(kuchar, subscriptionType)
X2S_FILL_SUB(MonetaryPrice, MonetaryPrice)
X2S_FILL_SUB(TotalNumberToken, TotalNumberToken)
X2S_FILL_SUB(SubscriptionPeriod, SubscriptionPeriod)
X2S_GOTO_PRT_NODE(PriceInfo)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PriceInfo)


X2S_FUN_DECL(Title)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Title)
X2S_GETNODECNT(Title)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Title)
X2S_SET_CNT(Title)
X2S_ALLOC_REC(Title)
X2S_FOREACH_NCNT(Title)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Title)
X2S_BRK_IF_BAD_NODE(Title)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, Title)
X2S_GOTO_PRT_NODE(Title)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Title)


X2S_FUN_DECL(PromotionExtension)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PromotionExtension)
X2S_GETNODECNT(PromotionExtension)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PromotionExtension)
X2S_SET_CNT(PromotionExtension)
X2S_ALLOC_REC(PromotionExtension)
X2S_FOREACH_NCNT(PromotionExtension)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PromotionExtension)
X2S_BRK_IF_BAD_NODE(PromotionExtension)
X2S_FILL_ATT(kpchar, url)
X2S_FILL_SUB(Description, Description)
X2S_GOTO_PRT_NODE(PromotionExtension)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PromotionExtension)


X2S_FUN_DECL(PromotionInfo)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PromotionInfo)
X2S_GETNODECNT(PromotionInfo)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PromotionInfo)
X2S_SET_CNT(PromotionInfo)
X2S_ALLOC_REC(PromotionInfo)
X2S_FOREACH_NCNT(PromotionInfo)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PromotionInfo)
X2S_BRK_IF_BAD_NODE(PromotionInfo)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kuint, validFrom)
X2S_FILL_ATT(kuint, validTo)
X2S_FILL_SUB(Title, Title)
X2S_FILL_SUB(TargetUserProfile, TargetUserProfile)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(PromotionExtension, PromotionExtension)
X2S_GOTO_PRT_NODE(PromotionInfo)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PromotionInfo)


X2S_FUN_DECL(PurchaseChannelReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseChannelReference)
X2S_GETNODECNT(PurchaseChannelReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseChannelReference)
X2S_SET_CNT(PurchaseChannelReference)
X2S_ALLOC_REC(PurchaseChannelReference)
X2S_FOREACH_NCNT(PurchaseChannelReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseChannelReference)
X2S_BRK_IF_BAD_NODE(PurchaseChannelReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(PurchaseChannelReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseChannelReference)


X2S_FUN_DECL(PreviwDataReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PreviwDataReference)
X2S_GETNODECNT(PreviwDataReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PreviwDataReference)
X2S_SET_CNT(PreviwDataReference)
X2S_ALLOC_REC(PreviwDataReference)
X2S_FOREACH_NCNT(PreviwDataReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PreviwDataReference)
X2S_BRK_IF_BAD_NODE(PreviwDataReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_ATT(kuchar, usage)
X2S_FILL_VAL(kpchar, PreviwDataReference)
X2S_GOTO_PRT_NODE(PreviwDataReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PreviwDataReference)


#if 0
X2S_FUN_DECL(PurchaseData)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseData)
X2S_GETNODECNT(PurchaseData)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseData)
X2S_SET_CNT(PurchaseData)
X2S_ALLOC_REC(PurchaseData)
X2S_FOREACH_NCNT(PurchaseData)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseData)
X2S_BRK_IF_BAD_NODE(PurchaseData)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(PriceInfo, PriceInfo)
X2S_FILL_SUB(PromotionInfo, PromotionInfo)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(PurchaseItemReference, PurchaseItemReference)
X2S_FILL_SUB(PurchaseChannelReference, PurchaseChannelReference)
X2S_FILL_SUB(PreviwDataReference, PreviwDataReference)
X2S_FILL_SUB(TermsOfUse, TermsOfUse)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(PurchaseData)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseData)
#endif


X2S_FUN_DECL(DistributionWindowID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(DistributionWindowID)
X2S_GETNODECNT(DistributionWindowID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(DistributionWindowID)
X2S_SET_CNT(DistributionWindowID)
X2S_ALLOC_REC(DistributionWindowID)
X2S_FOREACH_NCNT(DistributionWindowID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(DistributionWindowID)
X2S_BRK_IF_BAD_NODE(DistributionWindowID)
X2S_FILL_VAL(kuint, DistributionWindowID)
X2S_GOTO_PRT_NODE(DistributionWindowID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(DistributionWindowID)

X2S_FUN_DECL(ScheduleReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ScheduleReference)
X2S_GETNODECNT(ScheduleReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ScheduleReference)
X2S_SET_CNT(ScheduleReference)
X2S_ALLOC_REC(ScheduleReference)
X2S_FOREACH_NCNT(ScheduleReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ScheduleReference)
X2S_BRK_IF_BAD_NODE(ScheduleReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_SUB(PresentationWindowIDRef, PresentationWindowIDRef)
X2S_FILL_SUB(DistributionWindowID, DistributionWindowID)
X2S_GOTO_PRT_NODE(ScheduleReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ScheduleReference)


X2S_FUN_DECL(Dependencies)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Dependencies)
X2S_GETNODECNT(Dependencies)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Dependencies)
X2S_SET_CNT(Dependencies)
X2S_ALLOC_REC(Dependencies)
X2S_FOREACH_NCNT(Dependencies)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Dependencies)
X2S_BRK_IF_BAD_NODE(Dependencies)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(Dependencies)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Dependencies)


X2S_FUN_DECL(Exclusions)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Exclusions)
X2S_GETNODECNT(Exclusions)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Exclusions)
X2S_SET_CNT(Exclusions)
X2S_ALLOC_REC(Exclusions)
X2S_FOREACH_NCNT(Exclusions)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Exclusions)
X2S_BRK_IF_BAD_NODE(Exclusions)
X2S_FILL_ATT(kpchar, idRef)
X2S_GOTO_PRT_NODE(Exclusions)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Exclusions)

#if 0
X2S_FUN_DECL(PurchaseItem)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PurchaseItem)
X2S_GETNODECNT(PurchaseItem)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PurchaseItem)
X2S_SET_CNT(PurchaseItem)
X2S_ALLOC_REC(PurchaseItem)
X2S_FOREACH_NCNT(PurchaseItem)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PurchaseItem)
X2S_BRK_IF_BAD_NODE(PurchaseItem)
X2S_FILL_ATT(kpchar, globalPurchaseItemID)
X2S_FILL_ATT(kuint, binaryPurchaseItemID)
X2S_FILL_ATT(kushort, weight)
X2S_FILL_ATT(kbool, closed)
X2S_FILL_SUB(ServiceReference, ServiceReference)
X2S_FILL_SUB(ScheduleReference, ScheduleReference)
X2S_FILL_SUB(ContentReference, ContentReference)
X2S_FILL_SUB(PurchaseItemReference, PurchaseItemReference)
X2S_FILL_SUB(ProtectionKeyID, ProtectionKeyID)
X2S_FILL_SUB(Name, Name)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(StartTime, StartTime)
X2S_FILL_SUB(EndTime, EndTime)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(ParentalRating, ParentalRating)
X2S_FILL_SUB(Dependencies, Dependencies)
X2S_FILL_SUB(Exclusions, Exclusions)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(PurchaseItem)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PurchaseItem)
#endif



X2S_FUN_DECL(SMIL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SMIL)
X2S_GETNODECNT(SMIL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SMIL)
X2S_SET_CNT(SMIL)
X2S_ALLOC_REC(SMIL)
X2S_FOREACH_NCNT(SMIL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SMIL)
X2S_BRK_IF_BAD_NODE(SMIL)
X2S_FILL_ATT(kuchar, type)
X2S_FILL_VAL(kpchar, SMIL)
X2S_GOTO_PRT_NODE(SMIL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SMIL)


X2S_FUN_DECL(VideoURI)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(VideoURI)
X2S_GETNODECNT(VideoURI)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(VideoURI)
X2S_SET_CNT(VideoURI)
X2S_ALLOC_REC(VideoURI)
X2S_FOREACH_NCNT(VideoURI)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(VideoURI)
X2S_BRK_IF_BAD_NODE(VideoURI)
X2S_FILL_VAL(kpchar, VideoURI)
X2S_GOTO_PRT_NODE(VideoURI)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(VideoURI)


X2S_FUN_DECL(MIMEType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MIMEType)
X2S_GETNODECNT(MIMEType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MIMEType)
X2S_SET_CNT(MIMEType)
X2S_ALLOC_REC(MIMEType)
X2S_FOREACH_NCNT(MIMEType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MIMEType)
X2S_BRK_IF_BAD_NODE(MIMEType)
X2S_FILL_ATT(kpchar, codec)
X2S_FILL_VAL(kpchar, MIMEType)
X2S_GOTO_PRT_NODE(MIMEType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MIMEType)


X2S_FUN_DECL(AlternativeText)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AlternativeText)
X2S_GETNODECNT(AlternativeText)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AlternativeText)
X2S_SET_CNT(AlternativeText)
X2S_ALLOC_REC(AlternativeText)
X2S_FOREACH_NCNT(AlternativeText)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AlternativeText)
X2S_BRK_IF_BAD_NODE(AlternativeText)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, AlternativeText)
X2S_GOTO_PRT_NODE(AlternativeText)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AlternativeText)


X2S_FUN_DECL(AlternativePicture)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AlternativePicture)
X2S_GETNODECNT(AlternativePicture)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AlternativePicture)
X2S_SET_CNT(AlternativePicture)
X2S_ALLOC_REC(AlternativePicture)
X2S_FOREACH_NCNT(AlternativePicture)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AlternativePicture)
X2S_BRK_IF_BAD_NODE(AlternativePicture)
X2S_FILL_VAL(kpchar, AlternativePicture)
X2S_GOTO_PRT_NODE(AlternativePicture)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AlternativePicture)


X2S_FUN_DECL(Bitrate)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Bitrate)
X2S_GETNODECNT(Bitrate)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Bitrate)
X2S_SET_CNT(Bitrate)
X2S_ALLOC_REC(Bitrate)
X2S_FOREACH_NCNT(Bitrate)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Bitrate)
X2S_BRK_IF_BAD_NODE(Bitrate)
X2S_FILL_ATT(kushort, average)
X2S_FILL_ATT(kushort, maximum)
X2S_GOTO_PRT_NODE(Bitrate)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Bitrate)


X2S_FUN_DECL(Resolution)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Resolution)
X2S_GETNODECNT(Resolution)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Resolution)
X2S_SET_CNT(Resolution)
X2S_ALLOC_REC(Resolution)
X2S_FOREACH_NCNT(Resolution)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Resolution)
X2S_BRK_IF_BAD_NODE(Resolution)
X2S_FILL_ATT(kushort, horizontal)
X2S_FILL_ATT(kuchar, vertical)
X2S_FILL_ATT(kint, temporal)
X2S_GOTO_PRT_NODE(Resolution)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Resolution)


X2S_FUN_DECL(MinimumBufferSize)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MinimumBufferSize)
X2S_GETNODECNT(MinimumBufferSize)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MinimumBufferSize)
X2S_SET_CNT(MinimumBufferSize)
X2S_ALLOC_REC(MinimumBufferSize)
X2S_FOREACH_NCNT(MinimumBufferSize)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MinimumBufferSize)
X2S_BRK_IF_BAD_NODE(MinimumBufferSize)
X2S_FILL_VAL(kuint, MinimumBufferSize)
X2S_GOTO_PRT_NODE(MinimumBufferSize)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MinimumBufferSize)


X2S_FUN_DECL(Complexity)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Complexity)
X2S_GETNODECNT(Complexity)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Complexity)
X2S_SET_CNT(Complexity)
X2S_ALLOC_REC(Complexity)
X2S_FOREACH_NCNT(Complexity)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Complexity)
X2S_BRK_IF_BAD_NODE(Complexity)
X2S_FILL_SUB(Bitrate, Bitrate)
X2S_FILL_SUB(Resolution, Resolution)
X2S_FILL_SUB(MinimumBufferSize, MinimumBufferSize)
X2S_GOTO_PRT_NODE(Complexity)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Complexity)


X2S_FUN_DECL(Video)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Video)
X2S_GETNODECNT(Video)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Video)
X2S_SET_CNT(Video)
X2S_ALLOC_REC(Video)
X2S_FOREACH_NCNT(Video)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Video)
X2S_BRK_IF_BAD_NODE(Video)
X2S_FILL_SUB(VideoURI, VideoURI)
X2S_FILL_SUB(MIMEType, MIMEType)
X2S_FILL_SUB(AlternativeText, AlternativeText)
X2S_FILL_SUB(AlternativePicture, AlternativePicture)
X2S_FILL_SUB(Complexity, Complexity)
X2S_GOTO_PRT_NODE(Video)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Video)


X2S_FUN_DECL(AudioURI)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AudioURI)
X2S_GETNODECNT(AudioURI)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AudioURI)
X2S_SET_CNT(AudioURI)
X2S_ALLOC_REC(AudioURI)
X2S_FOREACH_NCNT(AudioURI)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AudioURI)
X2S_BRK_IF_BAD_NODE(AudioURI)
X2S_FILL_VAL(kpchar, AudioURI)
X2S_GOTO_PRT_NODE(AudioURI)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AudioURI)


X2S_FUN_DECL(Audio)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Audio)
X2S_GETNODECNT(Audio)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Audio)
X2S_SET_CNT(Audio)
X2S_ALLOC_REC(Audio)
X2S_FOREACH_NCNT(Audio)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Audio)
X2S_BRK_IF_BAD_NODE(Audio)
X2S_FILL_SUB(AudioURI, AudioURI)
X2S_FILL_SUB(MIMEType, MIMEType)
X2S_FILL_SUB(AlternativeText, AlternativeText)
X2S_FILL_SUB(AlternativePicture, AlternativePicture)
X2S_FILL_SUB(Complexity, Complexity)
X2S_GOTO_PRT_NODE(Audio)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Audio)


X2S_FUN_DECL(PictureURI)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PictureURI)
X2S_GETNODECNT(PictureURI)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PictureURI)
X2S_SET_CNT(PictureURI)
X2S_ALLOC_REC(PictureURI)
X2S_FOREACH_NCNT(PictureURI)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PictureURI)
X2S_BRK_IF_BAD_NODE(PictureURI)
X2S_FILL_VAL(kpchar, PictureURI)
X2S_GOTO_PRT_NODE(PictureURI)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PictureURI)


X2S_FUN_DECL(PictureData)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PictureData)
X2S_GETNODECNT(PictureData)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PictureData)
X2S_SET_CNT(PictureData)
X2S_ALLOC_REC(PictureData)
X2S_FOREACH_NCNT(PictureData)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PictureData)
X2S_BRK_IF_BAD_NODE(PictureData)
X2S_FILL_VAL(kpchar, PictureData)
X2S_GOTO_PRT_NODE(PictureData)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PictureData)


X2S_FUN_DECL(Picture)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Picture)
X2S_GETNODECNT(Picture)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Picture)
X2S_SET_CNT(Picture)
X2S_ALLOC_REC(Picture)
X2S_FOREACH_NCNT(Picture)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Picture)
X2S_BRK_IF_BAD_NODE(Picture)
X2S_FILL_SUB(PictureURI, PictureURI)
X2S_FILL_SUB(PictureData, PictureData)
X2S_FILL_SUB(MIMEType, MIMEType)
X2S_FILL_SUB(AlternativeText, AlternativeText)
X2S_GOTO_PRT_NODE(Picture)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Picture)


X2S_FUN_DECL(Text)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Text)
X2S_GETNODECNT(Text)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Text)
X2S_SET_CNT(Text)
X2S_ALLOC_REC(Text)
X2S_FOREACH_NCNT(Text)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Text)
X2S_BRK_IF_BAD_NODE(Text)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, Text)
X2S_GOTO_PRT_NODE(Text)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Text)


X2S_FUN_DECL(AccessReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AccessReference)
X2S_GETNODECNT(AccessReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AccessReference)
X2S_SET_CNT(AccessReference)
X2S_ALLOC_REC(AccessReference)
X2S_FOREACH_NCNT(AccessReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AccessReference)
X2S_BRK_IF_BAD_NODE(AccessReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_ATT(kuchar, usage)
X2S_FILL_VAL(kpchar, AccessReference)
X2S_GOTO_PRT_NODE(AccessReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AccessReference)

#if 0
X2S_FUN_DECL(PreviewData)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PreviewData)
X2S_GETNODECNT(PreviewData)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PreviewData)
X2S_SET_CNT(PreviewData)
X2S_ALLOC_REC(PreviewData)
X2S_FOREACH_NCNT(PreviewData)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PreviewData)
X2S_BRK_IF_BAD_NODE(PreviewData)
X2S_FILL_SUB(SMIL, SMIL)
X2S_FILL_SUB(Video, Video)
X2S_FILL_SUB(Audio, Audio)
X2S_FILL_SUB(Picture, Picture)
X2S_FILL_SUB(Text, Text)
X2S_FILL_SUB(AccessReference, AccessReference)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(PreviewData)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PreviewData)
#endif


X2S_FUN_DECL(AutoStart)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AutoStart)
X2S_GETNODECNT(AutoStart)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AutoStart)
X2S_SET_CNT(AutoStart)
X2S_ALLOC_REC(AutoStart)
X2S_FOREACH_NCNT(AutoStart)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AutoStart)
X2S_BRK_IF_BAD_NODE(AutoStart)
X2S_FILL_VAL(kuint, AutoStart)
X2S_GOTO_PRT_NODE(AutoStart)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AutoStart)


X2S_FUN_DECL(DistributionWindow)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(DistributionWindow)
X2S_GETNODECNT(DistributionWindow)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(DistributionWindow)
X2S_SET_CNT(DistributionWindow)
X2S_ALLOC_REC(DistributionWindow)
X2S_FOREACH_NCNT(DistributionWindow)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(DistributionWindow)
X2S_BRK_IF_BAD_NODE(DistributionWindow)
X2S_FILL_ATT(kuint, startTime)
X2S_FILL_ATT(kuint, endTime)
X2S_FILL_ATT(kuint, duration)
X2S_FILL_ATT(kuint, id)
X2S_GOTO_PRT_NODE(DistributionWindow)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(DistributionWindow)


X2S_FUN_DECL(InteractivityDataReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(InteractivityDataReference)
X2S_GETNODECNT(InteractivityDataReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(InteractivityDataReference)
X2S_SET_CNT(InteractivityDataReference)
X2S_ALLOC_REC(InteractivityDataReference)
X2S_FOREACH_NCNT(InteractivityDataReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(InteractivityDataReference)
X2S_BRK_IF_BAD_NODE(InteractivityDataReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_SUB(AutoStart, AutoStart)
X2S_FILL_SUB(DistributionWindow, DistributionWindow)
X2S_GOTO_PRT_NODE(InteractivityDataReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(InteractivityDataReference)


X2S_FUN_DECL(PresentationWindow)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PresentationWindow)
X2S_GETNODECNT(PresentationWindow)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PresentationWindow)
X2S_SET_CNT(PresentationWindow)
X2S_ALLOC_REC(PresentationWindow)
X2S_FOREACH_NCNT(PresentationWindow)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PresentationWindow)
X2S_BRK_IF_BAD_NODE(PresentationWindow)
X2S_FILL_ATT(kuint, startTime)
X2S_FILL_ATT(kuint, endTime)
X2S_FILL_ATT(kuint, duration)
X2S_FILL_ATT(kuint, id)
X2S_GOTO_PRT_NODE(PresentationWindow)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PresentationWindow)


X2S_FUN_DECL(ContentReference)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ContentReference)
X2S_GETNODECNT(ContentReference)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ContentReference)
X2S_SET_CNT(ContentReference)
X2S_ALLOC_REC(ContentReference)
X2S_FOREACH_NCNT(ContentReference)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ContentReference)
X2S_BRK_IF_BAD_NODE(ContentReference)
X2S_FILL_ATT(kpchar, idRef)
X2S_FILL_ATT(kpchar, contentLocation)
X2S_FILL_ATT(kpchar, audioLanguageIDRef)
X2S_FILL_ATT(kpchar, textLanguageIDRef)
X2S_FILL_ATT(kbool, repeatPlayback)
X2S_FILL_SUB(AutoStart, AutoStart)
X2S_FILL_SUB(DistributionWindow, DistributionWindow)
X2S_FILL_SUB(PresentationWindow, PresentationWindow)
X2S_GOTO_PRT_NODE(ContentReference)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ContentReference)

#if 0
X2S_FUN_DECL(Schedule)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Schedule)
X2S_GETNODECNT(Schedule)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Schedule)
X2S_SET_CNT(Schedule)
X2S_ALLOC_REC(Schedule)
X2S_FOREACH_NCNT(Schedule)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Schedule)
X2S_BRK_IF_BAD_NODE(Schedule)
X2S_FILL_ATT(kbool, defaultSchedule)
X2S_FILL_ATT(kbool, onDemand)
X2S_FILL_SUB(ServiceReference, ServiceReference)
X2S_FILL_SUB(InteractivityDataReference, InteractivityDataReference)
X2S_FILL_SUB(ContentReference, ContentReference)
X2S_FILL_SUB(PreviewDataReference, PreviewDataReference)
X2S_FILL_SUB(TermsOfUse, TermsOfUse)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(Schedule)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Schedule)
#endif



X2S_FUN_DECL(BSMFilterCode)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BSMFilterCode)
X2S_GETNODECNT(BSMFilterCode)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BSMFilterCode)
X2S_SET_CNT(BSMFilterCode)
X2S_ALLOC_REC(BSMFilterCode)
X2S_FOREACH_NCNT(BSMFilterCode)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BSMFilterCode)
X2S_BRK_IF_BAD_NODE(BSMFilterCode)
X2S_FILL_VAL(kuint, BSMFilterCode)
X2S_GOTO_PRT_NODE(BSMFilterCode)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BSMFilterCode)


X2S_FUN_DECL(RoamingRule)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(RoamingRule)
X2S_GETNODECNT(RoamingRule)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(RoamingRule)
X2S_SET_CNT(RoamingRule)
X2S_ALLOC_REC(RoamingRule)
X2S_FOREACH_NCNT(RoamingRule)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(RoamingRule)
X2S_BRK_IF_BAD_NODE(RoamingRule)
X2S_FILL_VAL(kpchar, RoamingRule)
X2S_GOTO_PRT_NODE(RoamingRule)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(RoamingRule)


X2S_FUN_DECL(BSMSelector)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BSMSelector)
X2S_GETNODECNT(BSMSelector)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BSMSelector)
X2S_SET_CNT(BSMSelector)
X2S_ALLOC_REC(BSMSelector)
X2S_FOREACH_NCNT(BSMSelector)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BSMSelector)
X2S_BRK_IF_BAD_NODE(BSMSelector)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kpchar, roamingRuleRequestAddress)
X2S_FILL_SUB(BSMFilterCode, BSMFilterCode)
X2S_FILL_SUB(Name, Name)
X2S_FILL_SUB(RoamingRule, RoamingRule)
X2S_GOTO_PRT_NODE(BSMSelector)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BSMSelector)


X2S_FUN_DECL(BSMList)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(BSMList)
X2S_GETNODECNT(BSMList)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(BSMList)
X2S_SET_CNT(BSMList)
X2S_ALLOC_REC(BSMList)
X2S_FOREACH_NCNT(BSMList)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(BSMList)
X2S_BRK_IF_BAD_NODE(BSMList)
X2S_FILL_SUB(BSMSelector, BSMSelector)
X2S_GOTO_PRT_NODE(BSMList)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(BSMList)


X2S_FUN_DECL(TimeGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TimeGroupingCriteria)
X2S_GETNODECNT(TimeGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TimeGroupingCriteria)
X2S_SET_CNT(TimeGroupingCriteria)
X2S_ALLOC_REC(TimeGroupingCriteria)
X2S_FOREACH_NCNT(TimeGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TimeGroupingCriteria)
X2S_BRK_IF_BAD_NODE(TimeGroupingCriteria)
X2S_FILL_ATT(kuint, startTime)
X2S_FILL_ATT(kuint, endTime)
X2S_GOTO_PRT_NODE(TimeGroupingCriteria)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TimeGroupingCriteria)


X2S_FUN_DECL(GenreGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(GenreGroupingCriteria)
X2S_GETNODECNT(GenreGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(GenreGroupingCriteria)
X2S_SET_CNT(GenreGroupingCriteria)
X2S_ALLOC_REC(GenreGroupingCriteria)
X2S_FOREACH_NCNT(GenreGroupingCriteria)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(GenreGroupingCriteria)
X2S_BRK_IF_BAD_NODE(GenreGroupingCriteria)
X2S_FILL_ATT(kpchar, type)
X2S_FILL_ATT(kpchar, href)
X2S_FILL_VAL(kpchar, GenreGroupingCriteria)
X2S_GOTO_PRT_NODE(GenreGroupingCriteria)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(GenreGroupingCriteria)


X2S_FUN_DECL(ServiceCriteria)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceCriteria)
X2S_GETNODECNT(ServiceCriteria)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceCriteria)
X2S_SET_CNT(ServiceCriteria)
X2S_ALLOC_REC(ServiceCriteria)
X2S_FOREACH_NCNT(ServiceCriteria)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceCriteria)
X2S_BRK_IF_BAD_NODE(ServiceCriteria)
X2S_FILL_VAL(kpchar, ServiceCriteria)
X2S_GOTO_PRT_NODE(ServiceCriteria)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceCriteria)


X2S_FUN_DECL(GroupingCriteria)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(GroupingCriteria)
X2S_GETNODECNT(GroupingCriteria)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(GroupingCriteria)
X2S_SET_CNT(GroupingCriteria)
X2S_ALLOC_REC(GroupingCriteria)
X2S_FOREACH_NCNT(GroupingCriteria)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(GroupingCriteria)
X2S_BRK_IF_BAD_NODE(GroupingCriteria)
X2S_FILL_SUB(TimeGroupingCriteria, TimeGroupingCriteria)
X2S_FILL_SUB(GenreGroupingCriteria, GenreGroupingCriteria)
X2S_FILL_SUB(BSMSelector, BSMSelector)
X2S_FILL_SUB(ServiceCriteria, ServiceCriteria)
X2S_GOTO_PRT_NODE(GroupingCriteria)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(GroupingCriteria)

X2S_FUN_DECL(Transport)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Transport)
X2S_GETNODECNT(Transport)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Transport)
X2S_SET_CNT(Transport)
X2S_ALLOC_REC(Transport)
X2S_FOREACH_NCNT(Transport)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Transport)
X2S_BRK_IF_BAD_NODE(Transport)

X2S_FILL_ATT(kuint, eID)
X2S_FILL_ATT(kuchar, TransportMode)
X2S_FILL_SUB(ServiceComponentID, ServiceComponentID)

X2S_FILL_ATT(kpchar, ipAddress)
X2S_FILL_ATT(kuint, port)
X2S_FILL_ATT(kpchar, srcIpAddress)
X2S_FILL_ATT(kushort, transmissionSessionID)
X2S_FILL_ATT(kulong, versionIDLength)
X2S_FILL_ATT(kbool, hasFDT)

X2S_GOTO_PRT_NODE(Transport)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Transport)

X2S_FUN_DECL(AlternativeAccessURL)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(AlternativeAccessURL)
X2S_GETNODECNT(AlternativeAccessURL)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(AlternativeAccessURL)
X2S_SET_CNT(AlternativeAccessURL)
X2S_ALLOC_REC(AlternativeAccessURL)
X2S_FOREACH_NCNT(AlternativeAccessURL)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(AlternativeAccessURL)
X2S_BRK_IF_BAD_NODE(AlternativeAccessURL)
X2S_FILL_VAL(kpchar, AlternativeAccessURL)
X2S_GOTO_PRT_NODE(AlternativeAccessURL)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(AlternativeAccessURL)


X2S_FUN_DECL(Fragment)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Fragment)
X2S_GETNODECNT(Fragment)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Fragment)
X2S_SET_CNT(Fragment)
X2S_ALLOC_REC(Fragment)
X2S_FOREACH_NCNT(Fragment)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Fragment)
X2S_BRK_IF_BAD_NODE(Fragment)
X2S_FILL_ATT(kuint, transportID)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kuint, version)
X2S_FILL_ATT(kuint, validFrom)
X2S_FILL_ATT(kuint, validTo)
X2S_FILL_ATT(kuchar, fragmentEncoding)
X2S_FILL_ATT(kuchar, fragmentType)
X2S_FILL_SUB(GroupingCriteria, GroupingCriteria)
X2S_GOTO_PRT_NODE(Fragment)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Fragment)


X2S_FUN_DECL(ServiceGuideDeliveryUnit)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceGuideDeliveryUnit)
X2S_GETNODECNT(ServiceGuideDeliveryUnit)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceGuideDeliveryUnit)
X2S_SET_CNT(ServiceGuideDeliveryUnit)
X2S_ALLOC_REC(ServiceGuideDeliveryUnit)
X2S_FOREACH_NCNT(ServiceGuideDeliveryUnit)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceGuideDeliveryUnit)
X2S_BRK_IF_BAD_NODE(ServiceGuideDeliveryUnit)
X2S_FILL_ATT(kuint, transportObjectID)
X2S_FILL_ATT(kpchar, contentLocation)
X2S_FILL_ATT(kuint, validFrom)
X2S_FILL_ATT(kuint, validTo)
X2S_FILL_SUB(Fragment, Fragment)
X2S_GOTO_PRT_NODE(ServiceGuideDeliveryUnit)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceGuideDeliveryUnit)

X2S_FUN_DECL(DescriptorEntry)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(DescriptorEntry)
X2S_GETNODECNT(DescriptorEntry)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(DescriptorEntry)
X2S_SET_CNT(DescriptorEntry)
X2S_ALLOC_REC(DescriptorEntry)
X2S_FOREACH_NCNT(DescriptorEntry)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(DescriptorEntry)
X2S_BRK_IF_BAD_NODE(DescriptorEntry)
X2S_FILL_SUB(GroupingCriteria, GroupingCriteria)
X2S_FILL_SUB(Transport, Transport)
X2S_FILL_SUB(AlternativeAccessURL, AlternativeAccessURL)
X2S_FILL_SUB(ServiceGuideDeliveryUnit, ServiceGuideDeliveryUnit)
X2S_GOTO_PRT_NODE(DescriptorEntry)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(DescriptorEntry)


#if 0
X2S_FUN_DECL(ServiceGuideDeliveryDescriptor)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceGuideDeliveryDescriptor)
X2S_GETNODECNT(ServiceGuideDeliveryDescriptor)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceGuideDeliveryDescriptor)
X2S_SET_CNT(ServiceGuideDeliveryDescriptor)
X2S_ALLOC_REC(ServiceGuideDeliveryDescriptor)
X2S_FOREACH_NCNT(ServiceGuideDeliveryDescriptor)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceGuideDeliveryDescriptor)
X2S_BRK_IF_BAD_NODE(ServiceGuideDeliveryDescriptor)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kuint, version)
X2S_FILL_SUB(NotificationReception, NotificationReception)
X2S_FILL_SUB(BSMList, BSMList)
X2S_FILL_SUB(DescriptorEntry, DescriptorEntry)
X2S_GOTO_PRT_NODE(ServiceGuideDeliveryDescriptor)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceGuideDeliveryDescriptor)
#endif



X2S_FUN_DECL(ServiceType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ServiceType)
X2S_GETNODECNT(ServiceType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ServiceType)
X2S_SET_CNT(ServiceType)
X2S_ALLOC_REC(ServiceType)
X2S_FOREACH_NCNT(ServiceType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ServiceType)
X2S_BRK_IF_BAD_NODE(ServiceType)
X2S_FILL_VAL(kuchar, ServiceType)
X2S_GOTO_PRT_NODE(ServiceType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ServiceType)


X2S_FUN_DECL(TerminalBindingKeyID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TerminalBindingKeyID)
X2S_GETNODECNT(TerminalBindingKeyID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TerminalBindingKeyID)
X2S_SET_CNT(TerminalBindingKeyID)
X2S_ALLOC_REC(TerminalBindingKeyID)
X2S_FOREACH_NCNT(TerminalBindingKeyID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TerminalBindingKeyID)
X2S_BRK_IF_BAD_NODE(TerminalBindingKeyID)
X2S_FILL_ATT(kpchar, tbkPermissionsIssuerURI)
X2S_GOTO_PRT_NODE(TerminalBindingKeyID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TerminalBindingKeyID)


X2S_FUN_DECL(GlobalServiceID)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(GlobalServiceID)
X2S_GETNODECNT(GlobalServiceID)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(GlobalServiceID)
X2S_SET_CNT(GlobalServiceID)
X2S_ALLOC_REC(GlobalServiceID)
X2S_FOREACH_NCNT(GlobalServiceID)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(GlobalServiceID)
X2S_BRK_IF_BAD_NODE(GlobalServiceID)
X2S_FILL_VAL(kpchar, GlobalServiceID)
X2S_GOTO_PRT_NODE(GlobalServiceID)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(GlobalServiceID)


X2S_FUN_DECL(PermissionsIssuerURI)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PermissionsIssuerURI)
X2S_GETNODECNT(PermissionsIssuerURI)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PermissionsIssuerURI)
X2S_SET_CNT(PermissionsIssuerURI)
X2S_ALLOC_REC(PermissionsIssuerURI)
X2S_FOREACH_NCNT(PermissionsIssuerURI)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PermissionsIssuerURI)
X2S_BRK_IF_BAD_NODE(PermissionsIssuerURI)
X2S_FILL_ATT(kbool, type)
X2S_GOTO_PRT_NODE(PermissionsIssuerURI)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PermissionsIssuerURI)


X2S_FUN_DECL(shape)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(shape)
X2S_GETNODECNT(shape)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(shape)
X2S_SET_CNT(shape)
X2S_ALLOC_REC(shape)
X2S_FOREACH_NCNT(shape)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(shape)
X2S_BRK_IF_BAD_NODE(shape)
X2S_GOTO_PRT_NODE(shape)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(shape)

#if 0
X2S_FUN_DECL(Service)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Service)
X2S_GETNODECNT(Service)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Service)
X2S_SET_CNT(Service)
X2S_ALLOC_REC(Service)
X2S_FOREACH_NCNT(Service)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Service)
X2S_BRK_IF_BAD_NODE(Service)
X2S_FILL_ATT(kushort, weight)
X2S_FILL_ATT(kbool, serviceContentProtection)
X2S_FILL_ATT(kpchar, baseCID)
X2S_FILL_ATT(kbool, emergency)
X2S_FILL_SUB(ProtectionKeyID, ProtectionKeyID)
X2S_FILL_SUB(ServiceType, ServiceType)
X2S_FILL_SUB(GlobalServiceID, GlobalServiceID)
X2S_FILL_SUB(Name, Name)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(AudioLanguage, AudioLanguage)
X2S_FILL_SUB(TextLanguage, TextLanguage)
X2S_FILL_SUB(ParentalRating, ParentalRating)
X2S_FILL_SUB(TargetUserProfile, TargetUserProfile)
X2S_FILL_SUB(Genre, Genre)
X2S_FILL_SUB(Extension, Extension)
X2S_FILL_SUB(PreviewDataReference, PreviewDataReference)
X2S_FILL_SUB(BroadcastArea, BroadcastArea)
X2S_FILL_SUB(TermsOfUse, TermsOfUse)
X2S_FILL_SUB(PrivateExt, PrivateExt)
X2S_GOTO_PRT_NODE(Service)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Service)
#endif



X2S_FUN_DECL(ActionDescriptor)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ActionDescriptor)
X2S_GETNODECNT(ActionDescriptor)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ActionDescriptor)
X2S_SET_CNT(ActionDescriptor)
X2S_ALLOC_REC(ActionDescriptor)
X2S_FOREACH_NCNT(ActionDescriptor)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ActionDescriptor)
X2S_BRK_IF_BAD_NODE(ActionDescriptor)
X2S_FILL_ATT(kuint, inputAllowedTime)
X2S_FILL_ATT(kpchar, onTimeOutPointer)
X2S_FILL_ATT(kbool, updateFlag)
X2S_FILL_ATT(kpchar, onActionPointer)
X2S_GOTO_PRT_NODE(ActionDescriptor)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ActionDescriptor)


X2S_FUN_DECL(PartType)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PartType)
X2S_GETNODECNT(PartType)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PartType)
X2S_SET_CNT(PartType)
X2S_ALLOC_REC(PartType)
X2S_FOREACH_NCNT(PartType)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PartType)
X2S_BRK_IF_BAD_NODE(PartType)
X2S_FILL_VAL(kpchar, PartType)
X2S_GOTO_PRT_NODE(PartType)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PartType)


X2S_FUN_DECL(Object)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Object)
X2S_GETNODECNT(Object)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Object)
X2S_SET_CNT(Object)
X2S_ALLOC_REC(Object)
X2S_FOREACH_NCNT(Object)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Object)
X2S_BRK_IF_BAD_NODE(Object)
X2S_FILL_ATT_(kpchar, Content_Location, "Content-Location")
X2S_FILL_ATT_(kpchar, Content_Type, "Content-Type")
X2S_FILL_ATT(kbool, start)
X2S_FILL_SUB(PartType, PartType)
X2S_GOTO_PRT_NODE(Object)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Object)


X2S_FUN_DECL(ChoiceText)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ChoiceText)
X2S_GETNODECNT(ChoiceText)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ChoiceText)
X2S_SET_CNT(ChoiceText)
X2S_ALLOC_REC(ChoiceText)
X2S_FOREACH_NCNT(ChoiceText)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ChoiceText)
X2S_BRK_IF_BAD_NODE(ChoiceText)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_VAL(kpchar, ChoiceText)
X2S_GOTO_PRT_NODE(ChoiceText)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ChoiceText)


X2S_FUN_DECL(SelectChoice)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SelectChoice)
X2S_GETNODECNT(SelectChoice)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SelectChoice)
X2S_SET_CNT(SelectChoice)
X2S_ALLOC_REC(SelectChoice)
X2S_FOREACH_NCNT(SelectChoice)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SelectChoice)
X2S_BRK_IF_BAD_NODE(SelectChoice)
X2S_FILL_ATT(kpchar, smsURI)
X2S_FILL_SUB(ChoiceText, ChoiceText)
X2S_GOTO_PRT_NODE(SelectChoice)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SelectChoice)


X2S_FUN_DECL(SMSTemplate)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(SMSTemplate)
X2S_GETNODECNT(SMSTemplate)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(SMSTemplate)
X2S_SET_CNT(SMSTemplate)
X2S_ALLOC_REC(SMSTemplate)
X2S_FOREACH_NCNT(SMSTemplate)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(SMSTemplate)
X2S_BRK_IF_BAD_NODE(SMSTemplate)
X2S_FILL_ATT(kuint, relativePreference)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(SelectChoice, SelectChoice)
X2S_GOTO_PRT_NODE(SMSTemplate)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(SMSTemplate)


X2S_FUN_DECL(MessageBody)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MessageBody)
X2S_GETNODECNT(MessageBody)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MessageBody)
X2S_SET_CNT(MessageBody)
X2S_ALLOC_REC(MessageBody)
X2S_FOREACH_NCNT(MessageBody)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MessageBody)
X2S_BRK_IF_BAD_NODE(MessageBody)
X2S_FILL_VAL(kpchar, MessageBody)
X2S_GOTO_PRT_NODE(MessageBody)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MessageBody)


X2S_FUN_DECL(EmailTemplate)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(EmailTemplate)
X2S_GETNODECNT(EmailTemplate)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(EmailTemplate)
X2S_SET_CNT(EmailTemplate)
X2S_ALLOC_REC(EmailTemplate)
X2S_FOREACH_NCNT(EmailTemplate)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(EmailTemplate)
X2S_BRK_IF_BAD_NODE(EmailTemplate)
X2S_FILL_ATT(kuint, relativePreference)
X2S_FILL_ATT(kpchar, toHeader)
X2S_FILL_ATT(kpchar, ccHeader)
X2S_FILL_ATT(kpchar, bccHeader)
X2S_FILL_ATT(kpchar, subjectHeader)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(MessageBody, MessageBody)
X2S_GOTO_PRT_NODE(EmailTemplate)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(EmailTemplate)


X2S_FUN_DECL(PhoneNumber)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PhoneNumber)
X2S_GETNODECNT(PhoneNumber)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PhoneNumber)
X2S_SET_CNT(PhoneNumber)
X2S_ALLOC_REC(PhoneNumber)
X2S_FOREACH_NCNT(PhoneNumber)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PhoneNumber)
X2S_BRK_IF_BAD_NODE(PhoneNumber)
X2S_FILL_VAL(kpchar, PhoneNumber)
X2S_GOTO_PRT_NODE(PhoneNumber)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PhoneNumber)



X2S_FUN_DECL(VoiceCall)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(VoiceCall)
X2S_GETNODECNT(VoiceCall)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(VoiceCall)
X2S_SET_CNT(VoiceCall)
X2S_ALLOC_REC(VoiceCall)
X2S_FOREACH_NCNT(VoiceCall)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(VoiceCall)
X2S_BRK_IF_BAD_NODE(VoiceCall)
X2S_FILL_ATT(kuint, relativePreference)
X2S_FILL_SUB(Description, Description)
X2S_FILL_SUB(PhoneNumber, PhoneNumber)
X2S_GOTO_PRT_NODE(VoiceCall)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(VoiceCall)


X2S_FUN_DECL(Weblink)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Weblink)
X2S_GETNODECNT(Weblink)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Weblink)
X2S_SET_CNT(Weblink)
X2S_ALLOC_REC(Weblink)
X2S_FOREACH_NCNT(Weblink)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Weblink)
X2S_BRK_IF_BAD_NODE(Weblink)
X2S_FILL_ATT(kuint, relativePreference)
X2S_FILL_ATT(kpchar, webURL)
X2S_FILL_SUB(Description, Description)
X2S_GOTO_PRT_NODE(Weblink)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Weblink)


X2S_FUN_DECL(MediaObjectSet)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MediaObjectSet)
X2S_GETNODECNT(MediaObjectSet)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MediaObjectSet)
X2S_SET_CNT(MediaObjectSet)
X2S_ALLOC_REC(MediaObjectSet)
X2S_FOREACH_NCNT(MediaObjectSet)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MediaObjectSet)
X2S_BRK_IF_BAD_NODE(MediaObjectSet)
X2S_FILL_ATT_(kpchar, xml_lang, "xml:lang")
X2S_FILL_ATT(kuint, relativePreference)
X2S_FILL_ATT_(kpchar, Content_Type, "Content-Type")
X2S_FILL_ATT_(kpchar, Content_Location, "Content-Location")
X2S_FILL_SUB(Description, Description)
// X2S_FILL_SUB(File, File)
X2S_FILL_SUB(Object, Object)
X2S_GOTO_PRT_NODE(MediaObjectSet)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MediaObjectSet)


X2S_FUN_DECL(MediaObjectGroup)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(MediaObjectGroup)
X2S_GETNODECNT(MediaObjectGroup)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(MediaObjectGroup)
X2S_SET_CNT(MediaObjectGroup)
X2S_ALLOC_REC(MediaObjectGroup)
X2S_FOREACH_NCNT(MediaObjectGroup)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(MediaObjectGroup)
X2S_BRK_IF_BAD_NODE(MediaObjectGroup)
X2S_FILL_ATT(kpchar, id)
X2S_FILL_ATT(kbool, startMediaFlag)
X2S_FILL_SUB(ActionDescriptor, ActionDescriptor)
X2S_FILL_SUB(BackOffTiming, BackOffTiming)
X2S_FILL_SUB(MediaObjectSet, MediaObjectSet)
X2S_FILL_SUB(SMSTemplate, SMSTemplate)
X2S_FILL_SUB(EmailTemplate, EmailTemplate)
X2S_FILL_SUB(VoiceCall, VoiceCall)
X2S_FILL_SUB(Weblink, Weblink)
X2S_FILL_SUB(AlternativeText, AlternativeText)
X2S_GOTO_PRT_NODE(MediaObjectGroup)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(MediaObjectGroup)

//X2S_FUN_DECL(PrivateExt)
//X2S_CURLY_BRACE_L
//X2S_DECL_VAR(PrivateExt)
//X2S_GETNODECNT(PrivateExt)
//X2S_CURLY_BRACE_L
//X2S_ALLOC_T(PrivateExt)
//X2S_SET_CNT(PrivateExt)
//X2S_ALLOC_REC(PrivateExt)
//X2S_FOREACH_NCNT(PrivateExt)
//X2S_CURLY_BRACE_L
//X2S_GOTO_iST_NODE(PrivateExt)
//X2S_BRK_IF_BAD_NODE(PrivateExt)
//X2S_FILL_VAL(kpchar, PrivateExt)
//X2S_GOTO_PRT_NODE(PrivateExt)
//X2S_CURLY_BRACE_R
//X2S_CURLY_BRACE_R
//X2S_RETURN_CURNODE
//X2S_CURLY_BRACE_R
//X2S_END_FUNCTION(PrivateExt)

//////////////////
X2S_FUN_DECL(PrivateExt)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(PrivateExt)
X2S_GETNODECNT(PrivateExt)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(PrivateExt)
X2S_SET_CNT(PrivateExt)
X2S_ALLOC_REC(PrivateExt)
X2S_FOREACH_NCNT(PrivateExt)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(PrivateExt)
X2S_BRK_IF_BAD_NODE(PrivateExt)
X2S_FILL_VAL(kpchar, PrivateExt)

X2S_FILL_SUB(BroadcastPara, BroadcastPara)

X2S_GOTO_PRT_NODE(PrivateExt)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(PrivateExt)

/*-----------------------------------------------------------------------
 * Bi-Direction SG Receive
 */
X2S_FUN_DECL(TS)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(TS)
X2S_GETNODECNT(TS)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(TS)
X2S_SET_CNT(TS)
X2S_ALLOC_REC(TS)
X2S_FOREACH_NCNT(TS)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(TS)
X2S_BRK_IF_BAD_NODE(TS)
X2S_FILL_ATT(kuint, TSID)
X2S_FILL_ATT(kuint, Frequency)
X2S_FILL_ATT(kpchar, TSName)
X2S_FILL_ATT(kpchar, TSDes)
X2S_FILL_ATT(kpchar, AURL)
X2S_GOTO_PRT_NODE(TS)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(TS)

X2S_FUN_DECL(Network)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Network)
X2S_GETNODECNT(Network)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Network)
X2S_SET_CNT(Network)
X2S_ALLOC_REC(Network)
X2S_FOREACH_NCNT(Network)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Network)
X2S_BRK_IF_BAD_NODE(Network)
X2S_FILL_ATT(kuint, NID)
X2S_FILL_ATT(kpchar, NName)
X2S_FILL_ATT(kpchar, NDes)
X2S_FILL_ATT(kuint, NType)
X2S_FILL_ATT(kpchar, AURL)
X2S_FILL_SUB(TS, TS)
X2S_GOTO_PRT_NODE(Network)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Network)

X2S_FUN_DECL(Networks)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(Networks)
X2S_GETNODECNT(Networks)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(Networks)
X2S_SET_CNT(Networks)
X2S_ALLOC_REC(Networks)
X2S_FOREACH_NCNT(Networks)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(Networks)
X2S_BRK_IF_BAD_NODE(Networks)
X2S_FILL_SUB(Network, Network)
X2S_GOTO_PRT_NODE(Networks)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(Networks)

X2S_FUN_DECL(ESG)
X2S_CURLY_BRACE_L
X2S_DECL_VAR(ESG)
X2S_GETNODECNT(ESG)
X2S_CURLY_BRACE_L
X2S_ALLOC_T(ESG)
X2S_SET_CNT(ESG)
X2S_ALLOC_REC(ESG)
X2S_FOREACH_NCNT(ESG)
X2S_CURLY_BRACE_L
X2S_GOTO_iST_NODE(ESG)
X2S_BRK_IF_BAD_NODE(ESG)
X2S_FILL_SUB(Networks, Networks)
X2S_GOTO_PRT_NODE(ESG)
X2S_CURLY_BRACE_R
X2S_CURLY_BRACE_R
X2S_RETURN_CURNODE
X2S_CURLY_BRACE_R
X2S_END_FUNCTION(ESG)

/*
 * End Bi-Direction SG Receive
 *----------------------------------------------------------------------*/
